name: Build Windows Executable

on:
  push:
    branches:
      - main  # Adjust if your branch is named differently
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile your_script.py

    - name: Archive and Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/
